runtime: nodejs20

instance_class: F2

env_variables:
  NODE_ENV: 'production'
  PORT: 8080

automatic_scaling:
  min_instances: 1
  max_instances: 2  # Lowered this value to avoid exceeding the limit

handlers:
  - url: /.*
    secure: always
    script: auto